name: CrimeTravelers
favicon: null
layout_spectrum: 0.016474548494443297
typography_spectrum: 0.0028302976861596107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5870163298677653
  lightness: 0.3543959390372038
  saturation: 0.8476498944219202
  rhythmicContrast: 0.04263448319397867
purpose: []
